# Uncomment the next line to define a global platform for your project

#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org/'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'xd_proprietor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xd_proprietor
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCShare/UI'
  pod 'UMCShare/Social/ReducedWeChat'
  pod 'UMCShare/Social/ReducedQQ'
  pod 'UMCShare/Social/ReducedSina'
  pod 'JCore', '2.1.4-noidfa'
  pod 'JPush', '3.2.4-noidfa'
  pod 'AFNetworking', '~> 3.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
  pod 'UICollectionViewLeftAlignedLayout', '~> 1.0.2'
  pod 'YYKit'
#  pod 'SDCycleScrollView'
  pod 'HMSegmentedControl'
  pod 'HCSStarRatingView', '~> 1.4.5'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'JXBWebKit', '~> 1.1.4'
  pod 'MBProgressHUD'
  pod 'Masonry'
  pod 'SDWebImage'

end
